version: '2'
services:
  jenkins_service:
    build: .
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
  target_service:
    build: 
      context: .
      dockerfile: target_dockerfile
    container_name: target_service
volumes:
  jenkins_home: