version: '2'
services:
  jenkins_service:
    build: .
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins
      - ./spring-boot-sample-atmosphere:/code
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home: